### ISSUE TITLE
Error during webpack build

### ISSUE THREAD

**Issue by ffox77** [CityOfZion/neo-electron-wallet#1]
Module not found: Error: Cannot resolve module 'history/lib/createHashHistory' in Projects/neo-electron-wallet/app
 @ ./app/index.js 48:24-64

**Comment by localhuman** [comment]
I ran into the same problem when running an older version of node, you'll need to upgrade!  We're currently running the LTS version 6.11.0

**Comment by Ejhfast** [comment]
Closed on #2
